name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
    - 'docs/**'
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  test:
    name: ${{ matrix.python-version }}-build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: ci/environment.yml
          cache-environment: true
          create-args: >-
            python=${{matrix.python-version}}

      - name: Install virtualizarr & icechunk tmp deps
        run: |
           python -m pip install -e . --no-deps
           python -m pip install git+https://github.com/mpiannucci/VirtualiZarr@icechunk
           python -m pip git+https://github.com/pydata/xarray@zarr-v3
           python -m pip git+https://github.com/mpiannucci/numcodecs@zarr3-codecs-beta-sync --no-deps

      - name: Running Icechunk Tests
        run: |
          python -m pytest ./virtualizarr/tests/test_writers/test_icechunk.py
